### ISSUE TITLE
spike: investigate how actions (tapOn, expectVisible, etc..) can be more extendable

### ISSUE THREAD

**Issue by wolfenrain** [wolfenrain/fluttium#11]
**Description**

Currently the actions are provided by Fluttium, but they are difficult to extend or add features to. It would be nice if we can define a way for creating custom actions, custom in the sense that Fluttium can easily use and create them but also custom in the sense that third-parties can bring their own actions to user flows.

**Requirements**

- [ ] Should support custom actions that are easily defined and easy to exectue for Fluttium.
- [ ] Should support bringing your own actions to your user flows.

**Comment by orestesgaolin** [comment]
I think some kind of "registry" pattern could be convenient. Currently actions are resolved in this [switch](https://github.com/wolfenrain/fluttium/blob/main/packages/fluttium_flow/lib/src/fluttium_action.dart#L19). If we could somehow globally register actions before running the tests, I would find it good enough. 

The registry could be populated in

-  either Dart `main` function 
- or some external yaml configuration file pointing to implementation of actions conforming to a known interface

**Comment by wolfenrain** [comment]
That was exactly the road I was going on as well for this! I was even looking into using Mason for people to write custom bricks that could tie into the Fluttium action ecosystem.

**Comment by wolfenrain** [comment]
## Idea outline

The idea is to have an optional `fluttium.yaml` file at the root of a project in which you can define any extra actions you need:

```yaml
actions:
  my_custom_action: ^0.1.0-dev.1
```

These actions are just packages on pub.dev but they have to follow a specific project structure:

```
my_custom_action/
├─ lib/
│  ├─ action.dart
├─ pubspec.yaml
```

The `action.dart` will contain a single method that will be used to register the custom action (and potentially other features) to the Fluttium driver. The only other requirement is that the `pubspec.yaml` has a dependency on a package from Fluttium to ensure that the action is supported on the version of Fluttium a user is running, but also it will allow us to provide data like arguments and such to the action.

The Fluttium driver can then generate a temporary package based on the `fluttium.yaml` where each action will be added as a dependency with the user's fluttium version as the constraint. Each action will then be exported by this package as well:

```dart
export 'package:my_custom_action/action.dart' as my_custom_action;
```

This temporary package will then be imported in the generated `.fluttium_driver.dart` that runs the user flow tests, and therefore have access to the custom actions thanks to the exports.

## Additional

- By having the packages as true dart/flutter packages, developers who create their own custom action have access to the whole ecosystem of [pub.dev](https://pub.dev) if they so choose.
- The pub.dev API can then be used to write a simple frontend as a store for pure fluttium actions by using the following API: `https://pub.dev/api/search?q=dependency%3A<PACKAGE_NAME>+<SEARCH_QUERY>`
- The Fluttium CLI will provide a command for creating custom actions and a command for easily adding an action to your `fluttium.yaml` 
- A global `fluttium.yaml` might also be interesting to support
