### ISSUE TITLE
fix: Screenshot in Linux distro

### ISSUE THREAD

**Issue by tee-jaay** [wolfenrain/fluttium#149]
**Description**

Screenshot is not working in Linux, with the fluttium tests running in Android emulator or Linux app (OpenSUSE).

**Steps To Reproduce**

Add take screenshot action in a test.yaml file

`- takeScreenshot: "screenshots/image_1.png"`

**Expected Behavior**

The image_1.png image file be located at  'screenshots/'

**Screenshots**

![Screenshot halted](https://res.cloudinary.com/jtam/image/upload/v1676832035/github/flutter/issue/screenshots-halt.png)

**Comment by wolfenrain** [comment]
The action isn't implemented on the current release, see https://github.com/wolfenrain/fluttium/issues/56#issuecomment-1282975253

The new version, which I hope to release next week will support screenshots on all platforms.

**Comment by wolfenrain** [comment]
With the new version released this should now be solved, closing this issue. If you still have issues pleas open a new issue thank you!
