### ISSUE TITLE
fix: fluttium update still available after updating - maybe wrong version?

### ISSUE THREAD

**Issue by novas1r1** [wolfenrain/fluttium#16]
**Description**
I just installed todays version of fluttium and it proposed to update from version "0.1.0-dev.35" to "0.1.0-dev.2" . So I ran `fluttium update`. Same proposal comes up again. I tried opening a new console, but the update proposal consists.

**Expected Behavior**
Fluttium gets updated and doesn't propose a newer version.

**Screenshots**
![image](https://user-images.githubusercontent.com/2575205/195830882-6181f86c-1868-4fbb-8891-8530073b1ac5.png)

**Additional Context**
```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale de-DE)
    • Flutter version 3.3.4 on channel stable at
      /Users/verenazaiser/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (vor 9 Tagen), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/verenazaiser/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • CA96C50A-3584-4880-836D-36CA535343E2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available```

**Comment by wolfenrain** [comment]
Seems I accidentally imported the `mason` version which is exported by the package, should be quick to fix.

@felangel any reason why the core package of mason has a package version exported? Considering the CLI for Mason has it's own versioning

**Comment by wolfenrain** [comment]
Reopening this, as I forgot to change a few more lines (woeps, too excited to fix the first reported bug)

**Comment by felangel** [comment]
> Seems I accidentally imported the `mason` version which is exported by the package, should be quick to fix.
> 
> @felangel any reason why the core package of mason has a package version exported? Considering the CLI for Mason has it's own versioning

It's exported because mason_cli needs to check whether the core version is compatible with a brick's environment when a user is generating code.

**Comment by MoezAyadiDev** [comment]
I had the same problem today in my Mac but not in windows Pc.

event I deactivate fluttium_cli and activate it again, I deleted it properly from flutter package and I install it from pub.dev

I'm not expert but the only difference for me. mason is installed only in my windows PC

**Comment by wolfenrain** [comment]
What exactly are you facing? If you install the latest version than the above problem is already fixed:

![image](https://user-images.githubusercontent.com/15887627/196169535-b582da83-c1a7-4cf3-91ec-da8bfa938a21.png)

**Comment by wolfenrain** [comment]
I think this is happening because the update command assumes it needs to update through the `dart pub` command but you have it installed using `flutter pub` (I assume).

**Comment by wolfenrain** [comment]
Can you open a new issue for this?
