### ISSUE TITLE
feat: Add a optional delay between actions for demo/debuging perposes

### ISSUE THREAD

**Issue by eb-so** [wolfenrain/fluttium#187]
**Description**

In this [tweet](https://twitter.com/wolfenrain/status/1628794055587921920) by @wolfenrain you can't clearly see what's happening due to the blazingly fast execution time 💨 
We want to have the option to add a pause between actions in order to make demos/debugging more slow and easy to watch

**Requirements**

- [ ] Either Add a new pause action or a global pause that adds a delay after every action
- [ ] Pause time will be in seconds
- [ ] Pause time can be customized

**Comment by wolfenrain** [comment]
I just merged and released #186 which will allow people to add artificial `wait`s between steps. So that should help slightly for the use cases of this issue.

**Comment by eb-so** [comment]
That's Awesome, I didn't know that
