### ISSUE TITLE
bug: Issues with my first fluttium run

### ISSUE THREAD

**Issue by Miiite** [wolfenrain/fluttium#202]
**Description**
When following the documentation to make my first run I encounter a number of issues:

- `fluttium init` is not a valid command:
```
fluttium init --verbose
Argument information:
  Top level options:
  - verbose: true
Could not find a command named "init".

Usage: fluttium <command> [arguments]

Global options:
-h, --help            Print this usage information.
-v, --version         Print the current version.
    --[no-]verbose    Noisy logging, including all shell commands executed.

Available commands:
  create   Create a FluttiumFlow test.
  test     Run a FluttiumFlow test.
  update   Update the CLI.

Run "fluttium help <command>" for more information about a command.
```

- When trying to update to the latest version, I appear to be stuck on the current one instead:
```
➜  super_app git:(develop) ✗ fluttium update
✓ Checked for updates (0.3s)
✓ Updated to 0.1.0-dev.18 (1.2s)
➜  super_app git:(develop) ✗ fluttium --version
0.1.0-dev.15

Update available! 0.1.0-dev.15 → 0.1.0-dev.18
Run fluttium update to update
```

- Finally when trying to make my first run with this test file:
```yaml
description: Init
---
- log: "Hello World!"
``` 

I end up with these logs:

```
fluttium test test.yaml --verbose
Argument information:
  Top level options:
  - verbose: true
  Command: test
    Command options:
✓ Retrieving devices (3.1s)
Unhandled exception:
UnimplementedError: log is not implemented
#0      FluttiumAction.resolve (package:fluttium_flow/src/fluttium_action.dart:32:9)
#1      new FluttiumStep.fromYaml (package:fluttium_flow/src/fluttium_step.dart:25:29)
#2      new FluttiumFlow (package:fluttium_flow/src/fluttium_flow.dart:17:49)
#3      FluttiumRunner._generateDriver (package:fluttium_runner/src/fluttium_runner.dart:170:12)
#4      FluttiumRunner.run (package:fluttium_runner/src/fluttium_runner.dart:193:11)
<asynchronous suspension>
#5      TestCommand.run (package:fluttium_cli/src/commands/test_command.dart:296:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      FluttiumCommandRunner.runCommand (package:fluttium_cli/src/command_runner.dart:111:18)
<asynchronous suspension>
#8      FluttiumCommandRunner.run (package:fluttium_cli/src/command_runner.dart:63:14)
<asynchronous suspension>
#9      main (file:///Users/adrien.padol/.pub-cache/hosted/pub.dartlang.org/fluttium_cli-0.1.0-dev.15/bin/fluttium.dart:6:24)
<asynchronous suspension>
```

**Additional Context**

My `fluttium.yaml` configuration file looks like this:

```yaml
environment:
  fluttium: ">=0.1.0-dev.1 <0.1.0"

driver:
  target: lib/main.dart
  dart_defines:
    - ... (here are a dozen of --dart-define)

# Register actions which can be used within your Fluttium flows.
actions:

```

**Comment by eb-so** [comment]
I have the same issue, I downloaded it using the cli

**Comment by eb-so** [comment]
<img width="844" alt="Screenshot 2023-03-07 at 11 56 39 PM" src="https://user-images.githubusercontent.com/89080323/223550725-3c91a6f8-de80-4517-8967-65e9a0a98a9e.png">
I opened the fluttium file in pub-cache/bin and here is what I found

**Comment by wolfenrain** [comment]
Ah, it installed the nearest version it can install because you have Dart 2.18. The newer version of Fluttium CLI needs at a minimal v2.19

**Comment by Miiite** [comment]
Ok so that's the same issue as mine, because I also had installed the CLI via pub.dev, but I am currently still on flutter `3.3.10`

**Comment by wolfenrain** [comment]
We should add a more clearer notice in the docs to reflect the minimal Dart/Flutter version needed.

**Comment by wolfenrain** [comment]
Closing this as Fluttium now checks before doing anything if the minimal Flutter version is available

**Comment by iam-shanmichael** [comment]
**Hello! folks**
- **as i follow the documentation for fluttium i encounter this issue:**

when i run  `fluttuim test map_fluttium` it install all components for fluttium but when i get in `intalling test runner` it's stuck in install or loading and didn't proceed to launch test runner that's why i can't run any flow because of this issue 

    `✓ Retrieving devices (7.8s)`
    `✓ Setting up the test runner (27ms)`
    `✓ Setting up the launcher (13ms)`
    `✓ Installing actions (2.2s)`
    `⠇ Installing test runner... (2000.8s)`

- Fluttium version:
    `0.1.2`
    
- Flutter doctor console result:

     ` [✓] Flutter (Channel stable, 3.7.6, on macOS 12.7 21G816 darwin-arm64, locale en-PH)`
         ` • Flutter version 3.7.6 on channel stable at /Users/SMGoring/fvm/versions/3.7.6`
         ` • Upstream repository https://github.com/flutter/flutter.git`
         ` • Framework revision 12cb4eb7a0 (9 months ago), 2023-03-01 10:29:26 -0800`
         ` • Engine revision ada363ee93`
          ` • Dart version 2.19.3`
        ` • DevTools version 2.20.1`
    
  `  [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)`
       ` • Android SDK at /Users/SMGoring/Library/Android/sdk`
      `  • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java`
        `• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)`
       ` • All Android licenses accepted.`
    
    `[!] Xcode - develop for iOS and macOS (Xcode 14.0)`
       ` • Xcode at /Applications/Xcode-beta.app/Contents/Developer`
        `• Build 14A5270f`
      `  ✗ CocoaPods not installed.`
           ` CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.`
            `Without CocoaPods, plugins will not work on iOS or macOS.`
           ` For more info, see https://flutter.dev/platform-plugins`
        `  To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.`
    
    `[✓] Chrome - develop for the web`
       ` • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome`
    
    `[✓] Android Studio (version 2021.2)`
        `• Android Studio at /Applications/Android Studio.app/Contents`
       ` • Flutter plugin can be installed from:`
         ` 🔨 https://plugins.jetbrains.com/plugin/9212-flutter`
        `• Dart plugin can be installed from:`
       `   🔨 https://plugins.jetbrains.com/plugin/6351-dart`
        `• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)`
    
    `[✓] VS Code (version 1.84.2)`
       ` • VS Code at /Users/SMGoring/Downloads/Visual Studio Code.app/Contents`
       `• Flutter extension version 3.76.0`
    
    `[✓] Connected device (2 available)`
       ` • macOS (desktop) • macos  • darwin-arm64   • macOS 12.7 21G816 darwin-arm64`
       `• Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159`
    
   ` [✓] HTTP Host Availability`
      `  • All required HTTP hosts are available`
      
 - This is my `Fluttium.yaml` :
 
    `# The following defines the environment for your Fluttium project. It includes`
    `# the version of Fluttium that the project requires.`
    `environment:`
      `fluttium: ">=0.1.0 <1.0.0"`
    
    `# The driver can be configured with default values. Uncomment the following `
    `# lines to automatically run Fluttium using a different flavor and dart-defines.`
    `# driver:`
    `#   target: lib/main_development.dart`
    `#   flavor: development`
    `#   dart_defines:`
    `#     - CUSTOM_DART_DEFINE=1`
    
    `# Register actions which can be used within your Fluttium flows.`
    `actions:`
      `# The following adds the log action to your project.`
      `log_action: 0.2.0`
