### ISSUE TITLE
fix: cannot to detect BottomNavigationBarItem

### ISSUE THREAD

**Issue by hifiaz** [wolfenrain/fluttium#225]
**Description**
i have bottom navigation bar and i add tooltip also on it but when run test bar item never found
`const BottomNavigationBarItem(
    tooltip: 'Create Event',
    icon: Icon(Icons.work),
    label: "Create Event",
  ),`

**Expected Behavior**

BottomNavigationBarItem can Expect Visible and Press on

**Comment by matthiasn** [comment]
I have the same issue.

**Comment by matthiasn** [comment]
@hifiaz I found a simple enough workaround. All you need to do is wrap the icon in each `BottomNavigationBarItem` in a `Semantics` widget, and then `pressOn` using the label assigned to the `Semantics` widget. I found that this only works if setting `image: true`.

```
    BottomNavigationBarItem(
      icon: Semantics(
        container: true,
        label: 'Habits Tab',
        image: true,
        child: const Icon(Icons.checklist_outlined),
      ),
      label: localizations.navTabTitleHabits,
      tooltip: '',
    ),
```

Also see in this [commit](https://github.com/matthiasn/lotti/pull/1480/commits/62556e8429f5021b02e138bbcd14968ea5f8d701) that shows the approach from above in context. Hope this helps.

**Comment by hifiaz** [comment]
thank you @matthiasn yes working good wrap with semantics as you suggest!
