### ISSUE TITLE
Utilize flutter_convenient_test (Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more)?

### ISSUE THREAD

**Issue by fzyzcjy** [wolfenrain/fluttium#30]
Hi, just come across this library :) Wondering whether https://github.com/fzyzcjy/flutter_convenient_test will be helpful, for example, to be used as lower-level implementation of this library?

(A video and intro can be seen here: https://github.com/fzyzcjy/flutter_convenient_test)

**Comment by wolfenrain** [comment]
Hi, I personally never heard of that package before and therefore I don't have any experience with it 😅.

What are potential ideas you had for it in combination with the goals that Fluttium is trying to achieve?

**Comment by fzyzcjy** [comment]
@wolfenrain Hi, maybe have a look at the readme which contains videos and introductions.

IMHO maybe these features are useful to be combined with Fluttium (for details see readme)

* Time travel, with screenshots
* Rapid re-execution
* Retryability
* Being interactive
* Isolated

**Comment by wolfenrain** [comment]
I am closing this issue as Fluttium no longer depends on the testing library and focus more on running full-blown apps as you normally would.

Thank you for the idea! And for pointing me to the existence of `flutter_convenient_test`

**Comment by fzyzcjy** [comment]
You are welcome and wish your package growing better and better!
