### ISSUE TITLE
fix: Update command not working properly

### ISSUE THREAD

**Issue by ramirezsebas** [wolfenrain/fluttium#311]
**Description**

I try to update the CLI but apparently its not updating.

**Steps To Reproduce**
1. Go to terminal
2. Run fluttium
3. Log shows that it need to be updated
4. Run fluttium update
5. See updated version
6. Run fluttium
7. Log shows that it need to be updated again

**Expected Behavior**

The command should update to the latest version of fluttium cli

**Screenshots**

<img width="709" alt="image" src="https://github.com/wolfenrain/fluttium/assets/61977214/ec435b7a-ffae-4f61-a73f-8352f54ce3a7">

<img width="448" alt="image" src="https://github.com/wolfenrain/fluttium/assets/61977214/0bbb7743-1704-4aac-bf84-2761303c9306">

<img width="673" alt="image" src="https://github.com/wolfenrain/fluttium/assets/61977214/95d0847c-0aaa-4822-920a-c00f8a2ad54b">

**Additional Context**

- This would be my current flutter version
<img width="734" alt="image" src="https://github.com/wolfenrain/fluttium/assets/61977214/83ccad94-d57f-4bbe-a587-8f9e5645f937">

- I have tried uninstalling and installing with:
flutter pub global activate fluttium_cli and flutter pub global deactivate fluttium_cli

**Comment by wolfenrain** [comment]
This is happening because you are on a pre Dart 3.0 Flutter version, and can't update to the `0.1.1` version which requires Dart 3.

The pub_updater package that I use does not check for that kind of version constraints.

**Comment by ramirezsebas** [comment]
I understand, so I would need to update my flutter and dart version?

**Comment by wolfenrain** [comment]
Yes, sadly the way Fluttium works its hard to be backwards compatible whenever Flutter breaks things, which they did.

**Comment by ramirezsebas** [comment]
Thank you for your timely response! Grateful for your help.
