### ISSUE TITLE
fix: Error When using `wait`, Fatal driver exception occurred: Expected a value of type 'int', but got one of type 'String'

### ISSUE THREAD

**Issue by ahmednfwela** [wolfenrain/fluttium#366]
**Description**

when using `wait` shorthand action

```yaml
- wait: 2000
```
I get this error:
```
 Fatal driver exception occurred: Expected a value of type 'int', but got one of type 'String'
```

or when I use this:
```yaml
- wait:
  seconds: 2
```

I get 
```
 Fatal driver exception occurred: Expected a value of type 'int', but got one of type 'Null'
```

looks like something is going horribly wrong when parsing integers, perhaps related to https://github.com/wolfenrain/fluttium/issues/365

**Comment by Thithip** [comment]
As the param file is YAML, you should be careful on indentation. I had same issues, but after some tests, I figure out that we need more space indentation for `wait`:
```yaml
- wait:
    seconds: 2
```

And not:
```yaml
- wait:
  seconds: 2
```

The `seconds` shouldn't be at the same level as `wait`.

Hope this help.

**Comment by ahmednfwela** [comment]
@Thithip Thanks a lot! that was indeed the fix

still the issue remains when using 
```yaml
- wait: 2000
```
