### ISSUE TITLE
fix: when using ' in strings, fluttium is crashing with "Error: String starting with ' must end with '."

### ISSUE THREAD

**Issue by novas1r1** [wolfenrain/fluttium#37]
**Description**
I checked for the text "I'M FINE, TAKE ME TO THE REGISTRATION" using `- expectVisible: "I'M FINE, LOGIN ANONYMOUSLY"`and my tests crashed and `fluttium --watch` wasn't able to restart the tests anymore. I had to rerun the `fluttium test my_flow.yaml --watch` command in order to receive the following error message:

```
.fluttium_driver.dart:35:63: Error: String starting with ' must end with '.
      await tester.expectVisible(r'I'M FINE, LOGIN ANONYMOUSLY');
```

**Steps To Reproduce**
1. Add `- expectVisible: "I'M FINE, LOGIN ANONYMOUSLY"` to my_flow.yaml
2. Run `fluttium test my_flow.yaml --watch`
3. Try to rerun tests with "r" command - shouldn't work
4. Repeat 2
5. See error message appearing

**Expected Behavior**
Fluttium should be able to handle texts including the ' character.

**Screenshots**
![image](https://user-images.githubusercontent.com/2575205/196042807-a2bde849-51b2-4b9e-960d-11f206099365.png)

**Comment by wolfenrain** [comment]
This should be easy fixed by sanitising all the string values! I'll tackle this later today.

Thank you for the bug report <3
