### ISSUE TITLE
docs: List supported platforms

### ISSUE THREAD

**Issue by bartekpacia** [wolfenrain/fluttium#45]
**Description**

I think it'd be useful to see which platforms are supported by Fluttium.

**Requirements**

- [x] No functional changes to the code

**Comment by wolfenrain** [comment]
As in the documentation should reflect that better? 

Right now it has tested support for iOS, macOS and android with Linux, Windows and web underway.

**Comment by bartekpacia** [comment]
> As in the documentation should reflect that better?

I actually haven't found any info in the docs about this (maybe I wasn't looking hard enough).

**Comment by wolfenrain** [comment]
Well yea fair point, i dont think I added it to the docs yet 😅 

So yes we should add that!

**Comment by wolfenrain** [comment]
@bartekpacia does #49 fill this gap for you?
