### ISSUE TITLE
fix: takeScreenshot seems to not work on Windows properly

### ISSUE THREAD

**Issue by md-weber** [wolfenrain/fluttium#56]
**Description**
On my windows computer, I tried to run the `takeScreenshot` command in an Android Emulator. It seems like the path to the file is not correctly set or cannot save the image correctly.

**Steps To Reproduce**

1. Use a windows computer
2. Execute the `takeScreenshot` command
3. Search for the File inside your project

**Expected Behavior**
- See the screenshot file in the folder declared inside the project

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8026644/196511801-992b59fa-cf21-4eab-b016-e99e1ea49b86.png)
![grafik](https://user-images.githubusercontent.com/8026644/196511875-ef1ddf04-3323-4246-a8f6-2cf4b8dda8cc.png)

**Additional Context**
What I tried:
- Using an absolute path
- Elevated terminal rights
- Using dynamic path

**Comment by wolfenrain** [comment]
With the new version released this should now be solved, closing this issue. If you still have issues pleas open a new issue thank you!
