### ISSUE TITLE
feat: Wait until something is on the screen

### ISSUE THREAD

**Issue by brunocalmels** [wolfenrain/fluttium#71]
**Description**

I'd like to use Fluttium to test an app that has a splash screen on startup. However, Fluttium seems to try to assert or perform an action straight on the first frame the app renders.

If there is a workaround, please let me know.

**Requirements**

- [ ] I should be able to wait until something is shown in order to proceed with further actions.

**Comment by wolfenrain** [comment]
#70 will help with that as it will introduce a wait for every action it tries to perform, as mentioned in #28 I am keen on having a dedicated action for it if it can be prevented.

I'll keep this issue open for now, as there might be valid use cases for having a dedicated action for waiting/sleeping but quite often it introduces flakiness into tests

**Comment by aidanmack** [comment]
Hey,
Similar issue to @brunocalmels . I too have a splash screen which is difficult to ui test right now.
I've pulled the latest changes which i think introduced a wait for every action, but I dont think the wait time is long enough for what I need.

I guess that this in its self is a bit of a code smell for the project im working on. 
(Something is happening and we can not verify it with a ui test)
I think maybe the issue stems from having async tasks that happen before the `runApp` widget is invoked.
For example initialising Firebase, shared prefs.

As its a project I've inherited right now it would be painful to refactor these async tasks to more appropriate area (i.e while splash screen shows), it would be ideal to have a dedicated wait function in fluttium.

**Comment by wolfenrain** [comment]
Currently that timeout is [10 seconds](https://github.com/wolfenrain/fluttium/blob/main/bricks/fluttium_driver/__brick__/.%7B%7Bflow_description.snakeCase()%7D%7D_driver.dart#L162) and I will make it configurable in the near future, but that would increase timeouts for all actions.

I might add a wait action just like [Maestro](https://maestro.mobile.dev/advanced/wait) does, but that requires me to refactor how the actions are managed (which I want to do in #11) to allow for better input handling. Which wont be done today or tomorrow 😓. 

As you mentioned it is indeed a bit of a code smell that you needing this but I get that it isn't easily refactored either. Sadly right now I cant provide you with a quick solution as both mentioned ones require quite a bit of work and testing to get it where it needs to be.

**Comment by aidanmack** [comment]
Thanks,
My splash screen only appears for 1 to 2 secs tops. 10 seconds should be more than enough. Maybe something is wrong with my test. I'll investigate more.

**Comment by aidanmack** [comment]
Apologies! It was my test, the timeout/wait you added works great. Thankyou!

**Comment by wolfenrain** [comment]
Glad to hear it! Hopefully when u really need a `wait`, i'll have it implemented by then 😂
