### ISSUE TITLE
feat: add `--dart-define` options to the CLI to pass to the Flutter process

### ISSUE THREAD

**Issue by aidanmack** [wolfenrain/fluttium#92]
**Description**

Fluttium is looking great, thankyou! 

Would it be possible to include some kind of setup yaml file maybe?
At build time my app requires run time arguments and I see no way of getting Fluttium to build with them.

**Comment by aidanmack** [comment]
Sure,

So  this is building the flutter project on the command line...
`flutter build ipa --flavor=prod --dart-define=CLIENT=terry_tibs --dart-define=BASE_URL=https://terrytibs.co.uk`

You can see that it builds an ipa
we set the `flavor` to `prod`
And then I can include any number of dart defined key values.

As an example I've passed in `client` and a `baseurl`

**Comment by wolfenrain** [comment]
Ah yea we can just expose `--dart-define` on the CLI, just like we did with the `flavor` and `target` options!

**Comment by aidanmack** [comment]
Nice!
So is there someway of me setting the `flavor` or `target` already before I run the test?

**Comment by aidanmack** [comment]
oh sorry I've just seen it in the docs 🤦

**Comment by wolfenrain** [comment]
I'll work on adding support for `dart-define` after I merge and release #70 (as it refactors the internal driver code, which this would touch)

**Comment by aidanmack** [comment]
Thanks man, appreciated!
